repos:
  - repo: local
    hooks:
      - id: poetry-version-bump
        name: Atualizar vers√£o com Poetry
        entry: bash -c 'poetry version patch && git add pyproject.toml'
        language: system
        pass_filenames: false
